### ISSUE TITLE
Synopsis tweaks

### ISSUE THREAD

**Issue by abbycabs** [mozillascience/software-citation-tools#2]
Synopsis is good! Left a PR https://github.com/mozillascience/software-citation-tools/pull/1 and a comment https://github.com/mozillascience/software-citation-tools/commit/f31ad33a1804b36664f0610e7d84d0d17f2b6963#commitcomment-19107022. Once both are addressed, I'll sign off on this!

Only two of you seem to be in the github team, so I'm assigning this to Eric & Rob.

**Comment by abbycabs** [comment]
@Faokryn & @sam1360 

![screen shot 2016-09-21 at 11 22 51](https://cloud.githubusercontent.com/assets/617994/18717408/c5c36340-7fed-11e6-8e03-c77d58ed4b08.png)

https://github.com/mozillascience

**Comment by faokryn** [comment]
My bad, I would have sworn I accepted that.  Should be good now.

**Comment by abbycabs** [comment]
awesome thanks all! Let me know your thoughts on this comment https://github.com/mozillascience/software-citation-tools/commit/f31ad33a1804b36664f0610e7d84d0d17f2b6963#commitcomment-19107022

**Comment by abbycabs** [comment]
emailed signed synopsis to everyone -- also attached here for reference. closing issue 💃 
[SoftwareCitationTools_synopsis.pdf](https://github.com/mozillascience/software-citation-tools/files/488179/SoftwareCitationTools_synopsis.pdf)
